---
title: "Bisection method"
author: "Alex Shen"
date: "2023-03-07"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bisection method in Rpubs

<https://rpubs.com/aaronsc32/bisection-method-r>
```{r}
bisection1 <- function(f, a, b, n = 1000, tol = 1e-7) {
  # If the signs of the function at the evaluated points, a and b, stop the function and return message.
  if (!(f(a) < 0) && (f(b) > 0)) {
    stop('signs of f(a) and f(b) differ')
  } else if ((f(a) > 0) && (f(b) < 0)) {
    stop('signs of f(a) and f(b) differ')
  }
  
  for (i in 1:n) {
    c <- (a + b) / 2 # Calculate midpoint
    
    # If the function equals 0 at the midpoint or the midpoint is below the desired tolerance, stop the 
    # function and return the root.
    if ((f(c) == 0) || ((b - a) / 2) < tol) {
      return(c)
    }
    
    # If another iteration is required, 
    # check the signs of the function at the points c and a and reassign
    # a or b accordingly as the midpoint to be used in the next iteration.
    ifelse(sign(f(c)) == sign(f(a)), 
           a <- c,
           b <- c)
  }
  # If the max number of iterations is reached and no root has been found, 
  # return message and end function.
  print('Too many iterations')
}
```

## Bisection method from ChatGPT
```{r}
bisection2 <- function(f, a, b, tol=1e-7, maxiter=1000) {
  # Input:
  #   f: the function to find roots of
  #   a, b: the interval [a,b] to search for roots
  #   tol: the tolerance for the root
  #   maxiter: the maximum number of iterations
  # Output:
  #   p: the root of the function
  
  # Initialize variables
  fa <- f(a)
  fb <- f(b)
  iter <- 0
  
  # Check if endpoints of interval have opposite signs
  if (fa * fb > 0) {
    stop("Endpoints of interval do not have opposite signs")
  }
  
  # Loop until convergence or maximum number of iterations reached
  while (iter < maxiter) {
    iter <- iter + 1
    
    # Compute midpoint
    p <- (a + b) / 2
    
    # Evaluate function at midpoint
    fp <- f(p)
    
    # Check if tolerance is met
    if (abs(fp) < tol) {
      return(p)
    }
    
    # Update interval
    if (fa * fp < 0) {
      b <- p
      fb <- fp
    } else {
      a <- p
      fa <- fp
    }
  }
  
  # Maximum number of iterations reached without convergence
  warning("Maximum number of iterations reached without convergence")
  return(p)
}

```

## Bisection from rdrr.io

<https://rdrr.io/cran/cmna/src/R/bisection.R>
```{r}
bisection3 <- function(f, a, b, tol = 1e-7, m = 100) {
    iter <- 0
    f.a <- f(a)
    f.b <- f(b)

    while (abs(b - a) > tol) {
        iter <- iter + 1
        if (iter > m) {
            warning("iterations maximum exceeded")
            break
        }
        xmid <- (a + b) / 2
        ymid <-  f(xmid)
        if (f.a * ymid > 0) {
            a <- xmid
            f.a <- ymid
        } else {
            b <- xmid
            f.b <- ymid
        }
    }

    ## Interpolate a midpoint for return value
    root <- (a + b) / 2
    return(root)
}
```


## The equation to solve for root
$$
x^3-2x-5 = 0
$$

```{r}
func <- function(x) {
  x^3 - 2 * x - 5
}

curve(func, xlim=c(-3,3), col='blue', lwd=1.5, lty=2)
abline(h=0)
abline(v=0)
```

## Root by bisection1
```{r}
root1 <- bisection1(func, 2, 3)
print(paste0("The root is approximately ", root1))
```

## Root by bisection2
```{r}
root2 <- bisection2(func,2,3)
print(paste0("The root is approximately ", root2))
```

## Root by bisection3
```{r}
root3 <-bisection3(func, 2, 3)
print(paste0("The root is approximately ", root3))
```

